### ISSUE TITLE
Creating an event from a group page yields a 404 page

### ISSUE THREAD

**Issue by tomelko** [softwareforgood/wordpress-commons#6]
Group event creation broken. Adding an event from /groups/all-commons/events/
goes to 404 /people/osc-admin/events/my-events/?action=edit&id=1

**Comment by evanheisler** [comment]
The starter database had event creation permissions turned off for all users. The fix is to go to `Events > Settings > General (tab) > Admin Tools` at the bottom of the page and reset default settings.
